// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BanUsers(arg1:Array<string>,arg2:string,arg3:boolean):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ConnectRcon(arg1:main.Credentials):Promise<boolean>;

export function DeleteCredentials():Promise<boolean>;

export function DisconnectRcon():Promise<boolean>;

export function GetConfig():Promise<main.Config>;

export function GetConfigField(arg1:string):Promise<any>;

export function GetLoadConfigPath():Promise<string>;

export function GetPlayers():Promise<Array<main.Player>>;

export function GetVersion():Promise<string>;

export function IsRconConnected():Promise<boolean>;

export function KickUsers(arg1:Array<string>,arg2:string):Promise<void>;

export function LoadCredentials():Promise<main.Credentials>;

export function OpenFileInExplorer(arg1:string):Promise<void>;

export function ReadConfig(arg1:string):Promise<void>;

export function RestartApplication(arg1:Array<string>):Promise<void>;

export function SaveConfigDialog():Promise<void>;

export function SaveCredentials(arg1:main.Credentials):Promise<boolean>;

export function SendNotification(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SendRconCommand(arg1:string):Promise<string>;

export function SendWindowsNotification(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetConfigField(arg1:string,arg2:any):Promise<void>;

export function UnbanUsers(arg1:Array<string>):Promise<void>;

export function Update(arg1:string):Promise<void>;
