// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConnectRcon(arg1) {
  return window['go']['main']['App']['ConnectRcon'](arg1);
}

export function DeleteCredentials() {
  return window['go']['main']['App']['DeleteCredentials']();
}

export function DisconnectRcon() {
  return window['go']['main']['App']['DisconnectRcon']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigField(arg1) {
  return window['go']['main']['App']['GetConfigField'](arg1);
}

export function GetLoadConfigPath() {
  return window['go']['main']['App']['GetLoadConfigPath']();
}

export function GetPlayers() {
  return window['go']['main']['App']['GetPlayers']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsRconConnected() {
  return window['go']['main']['App']['IsRconConnected']();
}

export function LoadCredentials() {
  return window['go']['main']['App']['LoadCredentials']();
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function ReadConfig(arg1) {
  return window['go']['main']['App']['ReadConfig'](arg1);
}

export function RestartApplication(arg1) {
  return window['go']['main']['App']['RestartApplication'](arg1);
}

export function SaveConfigDialog() {
  return window['go']['main']['App']['SaveConfigDialog']();
}

export function SaveCredentials(arg1) {
  return window['go']['main']['App']['SaveCredentials'](arg1);
}

export function SendNotification(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2, arg3, arg4);
}

export function SendRconCommand(arg1) {
  return window['go']['main']['App']['SendRconCommand'](arg1);
}

export function SendWindowsNotification(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendWindowsNotification'](arg1, arg2, arg3, arg4);
}

export function SetConfigField(arg1, arg2) {
  return window['go']['main']['App']['SetConfigField'](arg1, arg2);
}

export function Update(arg1) {
  return window['go']['main']['App']['Update'](arg1);
}
