// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlayer(arg1) {
  return window['go']['main']['App']['AddPlayer'](arg1);
}

export function AddPlayerToWhitelist(arg1, arg2) {
  return window['go']['main']['App']['AddPlayerToWhitelist'](arg1, arg2);
}

export function AddVehicle(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddVehicle'](arg1, arg2, arg3);
}

export function AddXp(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddXp'](arg1, arg2, arg3);
}

export function BanUsers(arg1, arg2, arg3) {
  return window['go']['main']['App']['BanUsers'](arg1, arg2, arg3);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConnectRcon(arg1) {
  return window['go']['main']['App']['ConnectRcon'](arg1);
}

export function CreateHorde(arg1, arg2) {
  return window['go']['main']['App']['CreateHorde'](arg1, arg2);
}

export function DeleteCredentials() {
  return window['go']['main']['App']['DeleteCredentials']();
}

export function DisconnectRcon() {
  return window['go']['main']['App']['DisconnectRcon']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigField(arg1) {
  return window['go']['main']['App']['GetConfigField'](arg1);
}

export function GetLoadConfigPath() {
  return window['go']['main']['App']['GetLoadConfigPath']();
}

export function GetPlayers() {
  return window['go']['main']['App']['GetPlayers']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GodMode(arg1, arg2) {
  return window['go']['main']['App']['GodMode'](arg1, arg2);
}

export function IsRconConnected() {
  return window['go']['main']['App']['IsRconConnected']();
}

export function KickUsers(arg1, arg2) {
  return window['go']['main']['App']['KickUsers'](arg1, arg2);
}

export function Lightning(arg1) {
  return window['go']['main']['App']['Lightning'](arg1);
}

export function LoadCredentials() {
  return window['go']['main']['App']['LoadCredentials']();
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function ReadConfig(arg1) {
  return window['go']['main']['App']['ReadConfig'](arg1);
}

export function RemovePlayersFromWhitelist(arg1, arg2) {
  return window['go']['main']['App']['RemovePlayersFromWhitelist'](arg1, arg2);
}

export function RestartApplication(arg1) {
  return window['go']['main']['App']['RestartApplication'](arg1);
}

export function SaveConfigDialog() {
  return window['go']['main']['App']['SaveConfigDialog']();
}

export function SaveCredentials(arg1) {
  return window['go']['main']['App']['SaveCredentials'](arg1);
}

export function SendNotification(arg1) {
  return window['go']['main']['App']['SendNotification'](arg1);
}

export function SendRconCommand(arg1) {
  return window['go']['main']['App']['SendRconCommand'](arg1);
}

export function SendWindowsNotification(arg1) {
  return window['go']['main']['App']['SendWindowsNotification'](arg1);
}

export function SetAccessLevel(arg1, arg2) {
  return window['go']['main']['App']['SetAccessLevel'](arg1, arg2);
}

export function SetConfigField(arg1, arg2) {
  return window['go']['main']['App']['SetConfigField'](arg1, arg2);
}

export function TeleportToCoordinates(arg1, arg2) {
  return window['go']['main']['App']['TeleportToCoordinates'](arg1, arg2);
}

export function TeleportToUser(arg1, arg2) {
  return window['go']['main']['App']['TeleportToUser'](arg1, arg2);
}

export function Thunder(arg1) {
  return window['go']['main']['App']['Thunder'](arg1);
}

export function UnbanUsers(arg1) {
  return window['go']['main']['App']['UnbanUsers'](arg1);
}

export function Update(arg1) {
  return window['go']['main']['App']['Update'](arg1);
}
